### ISSUE TITLE
asyncNNTP.py add_channel incorrect?

### ISSUE THREAD

**Issue by alok0** [madcowfred/newsmangler#1]
In more recent versions of python add_channel and del_channel have more parameters, so overriding these methods needs to match them, or else it trips up.

I know I've had this issue with 2.6 and 2.7

But since I am a python noob, I don't know if my fix is correct.

**Comment by madcowfred** [comment]
I've committed a fix for this but don't have an account I can test posting on right now - it should work though.

**Comment by alok0** [comment]
I did one test, seems to work as far as i can tell.
