### ISSUE TITLE
poll() for sockets under Win

### ISSUE THREAD

**Issue by JackDandy** [madcowfred/newsmangler#14]
Under windows,

python27 does contain asyncnntp, but postmangler.py fails to see this.

I suggest the following could be at fault...

```
    asyncore.poller = select.poll()
```

or perhaps you don't want to use the win poll, however, the reasons you had when first coding have most likely been fixed by the python team as documented in the file /Python27/NEWS.txt

thanks in advance

**Comment by madcowfred** [comment]
Apparently I fixed this in April and completely forgot to close the ticket, oops.
