### ISSUE TITLE
Generated .nzb is "wrong"

### ISSUE THREAD

**Issue by kouze** [madcowfred/newsmangler#15]
Hi

it seems that newsmangler generates "wrong" .nzb.
- NZB files number the parts of each file.
- The yEnc encoding protocol also numbers the parts of a file.
- In 99.99999% of NZB files, the numbering is identical with that of yEnc, which is defined in the NZB protocol: the numbering should match the actual order of the parts.

BUT, this is not the case in the .nzb generated by newsmangler.

The issue here is when we are using the generated .nzb file to download the data:
- If the client uses the NZB numbering, the data will be corrupted. In fact, the data are not at the right "place". This is the case for the majority of NZB clients (like newsbin, sabnzb or nzbget)
- If the client uses the yEnc numbering exclusively, the download is correct, but actually not supported by lots of clients (Newsleecher does this for example), and for sure not in line with NZB spec.

Could you then please adapt newsmangler to generate "correct" nzb file ?

Thanks !

**Comment by madcowfred** [comment]
Sorry for the late response, have been busy with school and completely forgot about this. I've committed a tentative fix in 3ed16a7, could you possibly test?

**Comment by kouze** [comment]
Hi,

for me the fix is ok. I tested both giganews and astraweb and for both server the .nzb is fine

Thanks!
