### ISSUE TITLE
Invalid XML for NZB files

### ISSUE THREAD

**Issue by pyrescene** [madcowfred/newsmangler#5]
I encountered a NZB file that I couldn't parse with [pynzb](http://pypi.python.org/pypi/pynzb/). This is because it wasn't valid XML.

```
<file poster="Yenc@power-post.org (Yenc-PP-A&A)" date="...
```

but at the bottom I saw this:

```
<!-- Generated by newsmangler at 2011-01-24 22:34:33 UTC -->
```

The issue here is the ampersand. [This](http://www.powergrep.com/manual/xmpxmlfixentities.html) is how you can fix them afterwards.
Add the following to _Common.py_ to fix the bug:

```
s = s.replace('&', '&amp;')
```

**Comment by madcowfred** [comment]
Thanks, fixed for now. I'll look into quoting XML entities properly at some point.

**Comment by pyrescene** [comment]
```
# Escape things properly to work as XML entities
def XMLBrackets(s):
    s = s.replace('<', '&lt;')
    s = s.replace('>', '&gt;')
    s = s.replace('"', '&#34;')
    s = s.replace('&', '&amp;')
    return s
```

It is fixed wrong. The ampersand replacement should be done first to not mess up the other replacements.

**Comment by madcowfred** [comment]
Derp. I've just made various changes including replacing the .nzb generation entirely with ElementTree, this is a much better idea than reinventing the wheel.
